# Generated by Django 5.2.8 on 2025-11-21 23:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupo_maximo', models.IntegerField(help_text='Cupo máximo por defecto para horarios de este curso', validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('regular', 'Curso Regular'), ('extension', 'Curso de Extensión')], default='regular', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, help_text='Costo para cursos de extensión', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('requisitos', models.TextField(blank=True, help_text='Prerrequisitos del curso')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('inscripcion_confirmada', 'Inscripción Confirmada'), ('inscripcion_cancelada', 'Inscripción Cancelada'), ('pago_recibido', 'Pago Recibido'), ('recordatorio', 'Recordatorio'), ('cambio_horario', 'Cambio de Horario')], max_length=30)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('intentos_envio', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Notificación por Email',
                'verbose_name_plural': 'Notificaciones por Email',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='PasarelaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'Mercado Pago'), ('payu', 'PayU')], max_length=20, unique=True)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('url_callback', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('configuracion_adicional', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pasarela de Pago',
                'verbose_name_plural': 'Pasarelas de Pago',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 2025-1', max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_inscripciones', models.DateField()),
                ('fecha_fin_inscripciones', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('rol', models.CharField(choices=[('admin_general', 'Administrador General'), ('admin_academico', 'Administrador Académico'), ('admin_financiero', 'Administrador Financiero')], default='admin_academico', max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_empleado', models.CharField(max_length=20, unique=True)),
                ('permisos_especiales', models.TextField(blank=True, help_text='Permisos adicionales separados por comas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True, verbose_name='Código de Estudiante')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Semestre Actual')),
                ('creditos_acumulados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Créditos Acumulados')),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Promedio General')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('W', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(max_length=50)),
                ('cupo_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupo_actual', models.IntegerField(default=0, help_text='Número de estudiantes inscritos actualmente', validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='UniNet_app.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='UniNet_app.periodo')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('retirada', 'Retirada')], default='pendiente', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('asistencia', models.IntegerField(default=0, help_text='Porcentaje de asistencia', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UniNet_app.estudiante')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UniNet_app.horario')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('pse', 'PSE')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('numero_transaccion', models.CharField(editable=False, max_length=100, unique=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='UniNet_app.inscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='UniNet_app.periodo'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_profesor', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email_institucional', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='UniNet_app.profesor'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscripciones', 'Reporte de Inscripciones'), ('pagos', 'Reporte de Pagos'), ('estudiantes', 'Reporte de Estudiantes'), ('cursos', 'Reporte de Cursos'), ('profesores', 'Reporte de Profesores')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('parametros', models.JSONField(blank=True, help_text='Filtros aplicados al reporte', null=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='UniNet_app.administrador')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Report',
            },
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('aula', 'dia_semana', 'hora_inicio', 'periodo')},
        ),
    ]
